FROM redhat/ubi8

RUN yum install net-tools -y

RUN yum install openssh-server -y

RUN yum install openssh-clients -y

RUN yum install httpd -y

RUN systemctl enable httpd

CMD ["httpd", "-D", "FOREGROUND"]

CMD ["sshd", "-D", "FOREGROUND"]

RUN mkdir -p /var/www/html/UAE

COPY "1032024.conf" "/etc/httpd/conf.d/UAE.conf"

COPY "index.html" "/var/www/html/UAE/index.html"

EXPOSE 82/tcp

CMD ["/usr/sbin/init"]
